config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root to: 'shops#index'

  resources :shops do
    resources :trackings do
      get :refresh
    end
  end

  resources :trackings

  get  ':token/search', to: 'search#show', defaults: { format: 'json' }
  get  ':token/search/:code', to: 'search#show', defaults: { format: 'json' }
  get  ':shop_name/:code', to: 'search#show'
  post 'intelipost/receive_hook', to: 'intelipost#create'
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  has_many :trackings, dependent: :destroy

  validates :slug, :name, :token, :host, presence: true

  before_validation :default_token, :default_slug

  protected

  def default_token
    self.token = SecureRandom.hex(16) unless token.presence
  end

  def default_slug
    self.slug = name&.parameterize
  end
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy]

  def index
    @shops = Shop.select('shops.*, count(trackings.id) as trackings_count')
      .left_joins(:trackings)
      .group('shops.id, trackings.shop_id')
      .order(:name)
  end

  def show
  end

  def new
    @shop = Shop.new
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html do
          redirect_to @shop, notice: 'Shop was successfully created.'
        end
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html do
          redirect_to @shop, notice: 'Shop was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shop.destroy
    respond_to do |format|
      format.html do
        redirect_to shops_url, notice: 'Shop was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit!
  end
end

app/helpers/shops_helper.rb
# frozen_string_literal: true

module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <%= render 'shared/error_messages', { resource: @shop } %>
  <fieldset>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :token %><br>
        <%= f.text_field :token, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :host %><br>
        <%= f.text_field :host, class: 'form-control' %>
        <small class="text-muted">Informe apenas o host. Ex.: www.vnda.com.br</small>
      </div>

      <hr />

      <h4>TNT</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :tnt_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :tnt_email %><br>
        <%= f.text_field :tnt_email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :tnt_cnpj %><br>
        <%= f.text_field :tnt_cnpj, class: 'form-control' %>
      </div>

      <hr />

      <h4>Intelipost</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :intelipost_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :forward_to_intelipost, class: 'form-check-input' %>
          Encaminhar códigos de rastreio
        </label>
      </div>

      <div class="form-group">
        <%= f.label :intelipost_id %><br>
        <%= f.text_field :intelipost_id, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :intelipost_api_key %><br>
        <%= f.text_field :intelipost_api_key, class: 'form-control' %>
      </div>

      <hr />

      <h4>Jadlog</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :jadlog_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :jadlog_password %><br>
        <%= f.text_field :jadlog_password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :jadlog_search_field %>
        <%= f.select :jadlog_search_field,
          Jadlog::SEARCH_FIELD_LIST.map{|field| [field, field] },
          {},
          class: "form-control"
        %>
      </div>

      <hr />

      <h4>Total Express</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :total_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :total_client_id %><br>
        <%= f.text_field :total_client_id, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :total_user %><br>
        <%= f.text_field :total_user, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :total_password %><br>
        <%= f.text_field :total_password, class: 'form-control' %>
      </div>

      <hr />

      <h4>Mandaê</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :mandae_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :mandae_token %><br>
        <%= f.text_field :mandae_token, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :mandae_pattern %><br>
        <%= f.text_field :mandae_pattern, class: 'form-control' %>
      </div>

      <hr />

      <h4>Melhor Envio</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :melhor_envio_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :melhor_envio_environment %>
        <%= f.select :melhor_envio_environment,
          MelhorEnvio::ENVIRONMENTS.map{|env| [I18n.translate(env, scope: 'environments'), env] },
          {},
          class: "form-control"
        %>
      </div>

      <hr />

      <h4>Loggi</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :loggi_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :loggi_token %><br>
        <%= f.text_field :loggi_token, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :loggi_email %><br>
        <%= f.text_field :loggi_email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :loggi_shop_id %><br>
        <%= f.text_field :loggi_shop_id, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :loggi_api_url %><br>
        <%= f.text_field :loggi_api_url, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :loggi_pattern %><br>
        <%= f.text_field :loggi_pattern, class: 'form-control' %>
      </div>

      <hr />

      <h4>Delivery Center</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :delivery_center_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :delivery_center_token %><br>
        <%= f.text_field :delivery_center_token, class: 'form-control' %>
      </div>

      <hr />

      <h4>Bling</h4>

      <div class="form-check">
        <label class="form-check-label">
          <%= f.check_box :bling_enabled, class: 'form-check-input' %>
          Habilitado
        </label>
      </div>

      <div class="form-group">
        <%= f.label :bling_api_key %><br>
        <%= f.text_field :bling_api_key, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :bling_status_in_transit %><br>
        <%= f.text_field :bling_status_in_transit, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :bling_status_delivered %><br>
        <%= f.text_field :bling_status_delivered, class: 'form-control' %>
      </div>

      <hr />

      <div class="actions">
        <%= f.submit 'Salvar', class: 'btn btn-primary' %>
        <%= link_to 'Cancelar', :back, class: 'btn btn-default'  %>
      </div>

      <br />
  </fieldset>
<% end %>

app/views/shops/edit.html.erb
<header class="page-header">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'Lojas', shops_path %></li>
      <li class="breadcrumb-item"><%= @shop.name %></li>
    </ol>
  </nav>
</header>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= render 'form' %>
  </div>
</div>

app/views/shops/index.html.erb
<div class="row page-header">
  <div class="col-lg-6">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to 'Lojas', shops_path %></li>
      </ol>
    </nav>
  </div>
  <div class="col-lg-6">
    <%= link_to('Adicionar', new_shop_url,
      class: 'btn btn-primary float-right') %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-shops table-striped table-hover small">
      <thead>
        <tr>
          <th>Loja</th>
          <th>Token</th>
          <th>Trackings</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% if @shops.any? %>
          <% @shops.each do |shop| %>
          <tr>
            <td><%= shop.name %></td>
            <td><%= shop.token %></td>
            <td class="text-center">
              <%= link_to "#{shop.trackings_count} trackings", shop_trackings_url(shop) %>
            </td>
            <td class="text-right">
              <div class="btn-group">
                <a href="<%= edit_shop_url(shop) %>" class="btn btn-secondary btn-sm">
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
                </a>

                <a href="<%= shop_url(shop) %>" class="btn btn-secondary btn-sm" data-method="delete" data-confirm="Tem certeza?">
                  <i class="fa fa-trash" aria-hidden="true"></i> Excluir
                </a>
              </div>
            </td>
          </tr>
          <% end %>
        <% else %>
        <tr>
          <td colspan="4" class="text-xs-center">
            <small>Nenhuma loja cadastrada</small>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shops/new.html.erb
<header class="page-header">
  <p>
    <%= link_to('← voltar', shops_url) %>
  </p>
  <h3>Adicionar Loja</h3>
</header>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= render 'form' %>
  </div>
</div>

app/views/shops/show.html.erb
<header class="page-header">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'Lojas', shops_path %></li>
      <li class="breadcrumb-item"><%= @shop.name %></li>
    </ol>
  </nav>
</header>

<dl class="row">
  <dt class="col-sm-3">Nome</dt>
  <dd class="col-sm-9"><%= @shop.name %></dd>

  <dt class="col-sm-3">Token</dt>
  <dd class="col-sm-9"><%= @shop.token %></dd>

  <dt class="col-sm-3">Host da loja </dt>
  <dd class="col-sm-9"><%= @shop.host %></dd>

  <dt class="col-sm-3">TNT habilitado</dt>
  <dd class="col-sm-9"><%= @shop.tnt_enabled %></dd>

  <dt class="col-sm-3">TNT e-mail</dt>
  <dd class="col-sm-9"><%= @shop.tnt_email %></dd>

  <dt class="col-sm-3">TNT CNPJ</dt>
  <dd class="col-sm-9"><%= @shop.tnt_cnpj  %></dd>
</dl>