config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root to: 'shops#index'

  resources :shops do
    resources :trackings do
      get :refresh
    end
  end

  resources :trackings

  get  ':token/search', to: 'search#show', defaults: { format: 'json' }
  get  ':token/search/:code', to: 'search#show', defaults: { format: 'json' }
  get  ':shop_name/:code', to: 'search#show'
  post 'intelipost/receive_hook', to: 'intelipost#create'
end

app/models/tracking.rb
# frozen_string_literal: true

class Tracking < ApplicationRecord
  STATUSES = %w[
    pending
    in_transit
    out_of_delivery
    delivered
    failed_attempt
    exception
    expired
  ].freeze

  belongs_to :shop
  has_many :events, class_name: 'TrackingEvent', dependent: :destroy
  has_many :notifications,
    class_name: 'TrackingNotification',
    dependent: :destroy

  validates :code, presence: true, if: ->(o) { o.carrier != 'intelipost' }
  validates :delivery_status, presence: :true
  validates :code, uniqueness: { scope: %i[shop_id carrier], allow_blank: true }

  before_validation :default_delivery_status, :discover_carrier,
    :discover_tracker_url
  after_commit :schedule_update, :forward_to_intelipost, on: [:create]

  def update_status!
    service = Carrier.new(shop, carrier)
    last_event = service.status(code)

    if last_event[:date].present?
      if 30.days.ago > last_event[:date]
        self.delivery_status = 'expired'
      elsif last_checkpoint_at.nil? || last_checkpoint_at < last_event[:date]
        self.delivery_status = last_event[:status]
        self.last_checkpoint_at = last_event[:date]
        self.last_response = service.last_response
      end

      if changed?
        save!
        TrackingEvent.register(service.events(code), self)
        return true
      end
    end

    false
  end

  def has_job?
    ss = Sidekiq::ScheduledSet.new
    job = ss.find do |e|
      [e['class'], e.args[0]] == ['RefreshTrackingStatus', id]
    end
    job.present?
  end

  private

  def forward_to_intelipost
    return unless shop.forward_to_intelipost

    Intelipost.new(shop).update_tracking(package, code)
  end

  def schedule_update
    RefreshTrackingStatus.perform_at(24.hours.from_now, id)
  end

  def discover_carrier
    self.carrier ||=
      if package&.include?(code)
        'intelipost'
      else
        Carrier.discover(code, shop)
      end
  end

  def discover_tracker_url
    if carrier == 'bling'
      return self.tracker_url ||= Bling.new(shop).tracking_url(package)
    end

    self.tracker_url ||= Carrier.url(
      carrier: carrier,
      code: code,
      shop: shop
    )
  end

  def default_delivery_status
    self.delivery_status ||= 'pending'
  end
end

app/controllers/trackings_controller.rb
# frozen_string_literal: true

class TrackingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_tracking, only: %i[show edit update destroy]

  # GET /trackings
  # GET /trackings.json
  def index
    @trackings = scopped_trackings.order(created_at: :desc)

    if params[:status].present?
      @trackings = @trackings.where(delivery_status: params[:status])
    end

    @scheduled_tracking_ids = Sidekiq::ScheduledSet.new.map do |j|
      j.args.first if j.klass == 'RefreshTrackingStatus'
    end
  end

  # GET /trackings/1
  # GET /trackings/1.json
  def show
  end

  # GET /trackings/new
  def new
    @tracking = scopped_trackings.new
  end

  # GET /trackings/1/edit
  def edit
  end

  # POST /trackings
  # POST /trackings.json
  def create
    @tracking = scopped_trackings.new(tracking_params)

    respond_to do |format|
      if @tracking.save
        format.html do
          redirect_to(
            shop_trackings_url(params[:shop_id]),
            notice: 'Tracking was successfully created.'
          )
        end
        format.json { render :show, status: :created, location: @tracking }
      else
        format.html { render :new }
        format.json do
          render json: @tracking.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /trackings/1
  # PATCH/PUT /trackings/1.json
  def update
    respond_to do |format|
      if @tracking.update(tracking_params)
        format.html do
          redirect_to(
            shop_trackings_url(params[:shop_id]),
            notice: 'Tracking was successfully updated.'
          )
        end
        format.json { render :show, status: :ok, location: @tracking }
      else
        format.html { render :edit }
        format.json do
          render json: @tracking.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /trackings/1
  # DELETE /trackings/1.json
  def destroy
    @tracking.destroy
    respond_to do |format|
      format.html do
        redirect_to(
          shop_trackings_url(params[:shop_id]),
          notice: 'Tracking was successfully destroyed.'
        )
      end
      format.json { head :no_content }
    end
  end

  def refresh
    RefreshTrackingStatus.perform_async(params[:tracking_id])
    respond_to do |format|
      format.html do
        redirect_to(
          shop_trackings_url(params[:shop_id]),
          notice: 'Refresh Tracking scheduled.'
        )
      end
      format.json { head :no_content }
    end
  end

  private

  def shop
    @shop ||=
      if params[:token].present?
        Shop.where(token: params[:token]).first
      else
        Shop.find(params[:shop_id])
      end
  end

  def tracking_params
    params.require(:tracking).permit(:code, :package, :carrier,
      :notification_url, :delivery_status, :tracker_url)
  end

  def set_tracking
    @tracking = scopped_trackings.find(params[:id])
  end

  def scopped_trackings
    @trackings ||= shop.trackings
  end
end

app/helpers/trackings_helper.rb
# frozen_string_literal: true

module TrackingsHelper
end

app/views/trackings/_form.html.erb
<% form_url = @tracking.id.present? ? shop_tracking_path(params[:shop_id], @tracking.id) : shop_trackings_path(params[:shop_id])%>
<%= form_for(@tracking, url: form_url ) do |f| %>
  <%= render 'shared/error_messages', { resource: @tracking } %>
  <fieldset>
      <div class="form-group">
        <%= f.label :code %>
        <%= f.text_field :code, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :carrier %>
        <%= f.text_field :carrier, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :delivery_status %>
        <%= f.select(:delivery_status, Tracking::STATUSES.map { |status| [I18n.translate(status, scope: :delivery_status), status] }, {}, class: 'form-control') %>
      </div>

      <div class="form-group">
        <%= f.label :tracker_url %>
        <%= f.text_field :tracker_url, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit 'Salvar', class: 'btn btn-primary' %>
        <%= link_to 'Cancelar', :back, class: 'btn btn-default'  %>
      </div>
  </fieldset>
<% end %>

app/views/trackings/edit.html.erb
<header class="page-header">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'Lojas', shops_path %></li>
      <li class="breadcrumb-item"><%= link_to @shop.name, shop_path(@shop) %></li>
      <li class="breadcrumb-item"><%= link_to 'Rastreios', shop_trackings_path(@shop) %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @tracking.code %></li>
    </ol>
  </nav>
</header>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= render 'form', tracking: @tracking %>
  </div>
</div>

app/views/trackings/index.html.erb
<div class="row page-header mb-0">
  <div class="col-lg-6">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to 'Lojas', shops_path %></li>
        <li class="breadcrumb-item"><%= link_to @shop.name, shop_path(@shop) %></li>
        <li class="breadcrumb-item active" aria-current="page">Rastreios</li>
      </ol>
    </nav>
  </div>
  <div class="col-lg-6">
    <%= link_to('Adicionar', new_shop_tracking_path(params[:shop_id]),
      class: 'btn btn-primary float-right') %>
  </div>
</div>

<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Status da entrega
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <a class="dropdown-item" href="?">
        <span class="text-center" style="min-width: 20px; display: inline-block;">
        </span>
        Todos
      </a>
      <% Tracking::STATUSES.each do |status| %>
        <a class="dropdown-item" href="?status=<%= status %>">
          <span class="text-center" style="min-width: 20px; display: inline-block;">
            <i class='fas <%=t status, scope: :delivery_status_icon %>'></i>
          </span>
          <%=t status, scope: :delivery_status %>
        </a>
      <% end %>
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-shops table-striped table-hover small">
      <thead>
        <tr>
          <th><%=t 'code', scope: [:activerecord, :attributes, :tracking] %></th>
          <th><%=t 'package', scope: [:activerecord, :attributes, :tracking] %></th>
          <th><%=t 'carrier', scope: [:activerecord, :attributes, :tracking] %></th>
          <th><%=t 'delivery_status', scope: [:activerecord, :attributes, :tracking] %></th>
          <th><%=t 'tracker_url', scope: [:activerecord, :attributes, :tracking] %></th>
          <th>Job</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% if @trackings.any? %>
          <% @trackings.each do |tracking| %>
          <tr>
            <td><%= tracking.code %></td>
            <td><%= tracking.package %></td>
            <td><%= tracking.carrier %></td>
            <td class="text-center">
              <i title='<%=t tracking.delivery_status, scope: :delivery_status %>' class='fas <%=t tracking.delivery_status, scope: :delivery_status_icon %> fa-2x'></i>
            </td>
            <td><%= link_to_if(tracking.tracker_url.present?, tracking.tracker_url, tracking.tracker_url, target: "_blank") %></td>
            <td>
              <% if @scheduled_tracking_ids.include?(tracking.id) %>
                Rastreando
              <% elsif tracking.delivery_status != 'delivered' %>
                <a href="<%= shop_tracking_refresh_path(params[:shop_id], tracking) %>" class="btn btn-secondary btn-sm">
                  <i class="fa fa-play" aria-hidden="true"></i> Rastrear
                </a>
              <% end %>
            </td>
            <td class="text-xs-right">
              <div class="btn-group">
                <a href="<%= shop_tracking_path(params[:shop_id], tracking) %>" class="btn btn-secondary btn-sm">
                  <i class="fa fa-search" aria-hidden="true"></i> Ver
                </a>

                <a href="<%= edit_shop_tracking_path(params[:shop_id], tracking) %>" class="btn btn-secondary btn-sm">
                  <i class="fa fa-edit" aria-hidden="true"></i> Editar
                </a>

                <a href="<%= shop_tracking_path(params[:shop_id], tracking) %>" class="btn btn-secondary btn-sm" data-method="delete" data-confirm="Tem certeza?">
                  <i class="fa fa-trash" aria-hidden="true"></i> Excluir
                </a>
              </div>
            </td>
          </tr>
          <% end %>
        <% else %>
        <tr>
          <td colspan="7" class="text-xs-center">
            <small>Nenhum tracking cadastrado</small>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/trackings/new.html.erb
<header class="page-header">
  <p>
    <%= link_to('← voltar', shop_trackings_path(params[:shop_id])) %>
  </p>
  <h3>Adicionar Rastreio</h3>
</header>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= render 'form' %>
  </div>
</div>

app/views/trackings/show.html.erb
<header class="page-header">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'Lojas', shops_path %></li>
      <li class="breadcrumb-item"><%= link_to @shop.name, shop_path(@shop) %></li>
      <li class="breadcrumb-item"><%= link_to 'Rastreios', shop_trackings_path(@shop) %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @tracking.code %></li>
    </ol>
  </nav>
</header>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <dl class="row">
      <% @tracking.attributes.each do |k, v| %>
        <dt class="col-sm-4"><%=t k, scope: [:activerecord, :attributes, :tracking] %></dt>
        <dd class="col-sm-8"><%= v %></dd>
      <% end %>
    </dl>
  </div>
</div>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <table class="table table-shops table-striped table-hover small">
      <thead>
        <tr>
          <th>Data</th>
          <th>Status</th>
          <th>Menssagem</th>
        </tr>
      </thead>
      <tbody>
        <% @tracking.events.order(:checkpoint_at).each do |event| %>
        <tr>
          <td><%= event.checkpoint_at %></td>
          <td class="text-center"><i title='<%=t event.delivery_status, scope: :delivery_status %>' class='fas <%=t event.delivery_status, scope: :delivery_status_icon %> fa-2x'></i></td>
          <td><%= event.message %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>